### PR TITLE
[WIP] Add new Trends Graphs with filters

### PR DESCRIPTION
**Pull request by adam-thorpe**
- Modified existing Tracking graph to now include many more filters
- Added new Monthly Graph with filters

Tested with localhost results, awaiting API changes to be merged into master

Closes: **https://github.com/AdoptOpenJDK/openjdk-dashboard-v2/issues/6**

Signed-off-by: Adam Thorpe <adam.thorpe@ibm.com>

### CODE REVIEW

**Comment by karianna** [comment]
@adam-thorpe is this still WIP or shall I land it?

**Comment by adam-thorpe** [comment]
@karianna I've got a few minor bugs to fix and I wanted to test it with all the API changes first so will let you know when it's ready :)

**Comment by adam-thorpe** [comment]
Just awaiting API changes now

**Comment by karianna** [comment]
> Just awaiting API changes now

Pretty sure they landed a few days ago, are you not seeing that?

**Comment by adam-thorpe** [comment]
No.. https://github.com/AdoptOpenJDK/openjdk-api-v3/commit/04f84bf8957ef0d8588867adeca5804923f1fcc1 and https://github.com/AdoptOpenJDK/openjdk-api-v3/commit/3aef4e6b6f0940b884a8a0b456e5105f75b678ab aren't in master, else I would be expecting https://api.adoptopenjdk.net/v3/stats/downloads/monthly to return something sane

**Comment by karianna** [comment]
@johnoliver - Can we get a merge into `master` at your convenience?

**Comment by smlambert** [comment]
@andrew-m-leonard - can you please create issues for the review requests that were not addressed, without addressing them in this PR, technical debt has been introduced

**Comment by andrew-m-leonard** [comment]
ref: https://github.com/AdoptOpenJDK/openjdk-dashboard-v2/issues/9

**Comment by andrew-m-leonard** [comment]
> @andrew-m-leonard - can you please create issues for the review requests that were not addressed, without addressing them in this PR, technical debt has been introduced

dnoe: https://github.com/AdoptOpenJDK/openjdk-dashboard-v2/issues/9

**Comment by andrew-m-leonard** [comment]
ref: https://github.com/AdoptOpenJDK/openjdk-dashboard-v2/issues/10

**Comment by karianna** [comment]
run-tests

**Comment by andrew-m-leonard** [comment]
@karianna should this be visible/live now? https://dash-v2.adoptopenjdk.net/trends is still only showing old chart

**Comment by karianna** [comment]
Still fixing #8

**Pull request merged**
